MVCLog/MVCLog/Models/ErrorViewModel.cs
using System;

namespace MVCLog.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCLog/MVCLog/Models/LogViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCLog.Models
{
    public class LogViewModel
    {
        public int Id { get; set; }

        public string Ip { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }

        public DateTime Date { get; set; }

    }
}

MVCLog/MVCLog/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVCLog.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MVCLog.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCLog/MVCLog/Controllers/LogController.cs
using Microsoft.AspNetCore.Mvc;
using MVCLog.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace MVCLog.Controllers
{
    public class LogController : Controller
    {
        private readonly string apiUrl = "https://localhost:44334/api/log";
        public async Task<IActionResult> Index()
        {
            List<LogViewModel> listLogs = new List<LogViewModel>();
            int page = 1;
            int take = 50;
            int totalLogs = 0;
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(apiUrl  +"/pagination/" + page + "/" + take))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    listLogs = JsonConvert.DeserializeObject<List<LogViewModel>>(apiResponse);
                }

                using (var response = await httpClient.GetAsync(apiUrl + "/countAll/"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    ViewBag.Total = apiResponse;
                    totalLogs = System.Convert.ToInt32(ViewBag.Total);
                }
            }
            var pages = (totalLogs + 9) / take;
            ViewData["qtdPagina"] = pages;
            ViewData["pagina"] = page;
            return View(listLogs);
        }

        [HttpPost]
        public async Task<IActionResult> Index(int page)
        {
            List<LogViewModel> listLogs = new List<LogViewModel>();
            int take = 50;
            int totalLogs = 0;
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(apiUrl + "/pagination/" + page + "/" + take))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    listLogs = JsonConvert.DeserializeObject<List<LogViewModel>>(apiResponse);
                }

                using (var response = await httpClient.GetAsync(apiUrl + "/countAll/"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    ViewBag.Total = apiResponse;
                    totalLogs = System.Convert.ToInt32(ViewBag.Total);
                }
            }
            var pages = (totalLogs + 9) / take;
            ViewData["qtdPagina"] = pages;
            ViewData["pagina"] = page;
            return View(listLogs);
        }


        [HttpPost]
        public async Task<IActionResult> Search(DateTime initial,DateTime final, string description, int id, string ip)
        {
            List<LogViewModel> listLogs = new List<LogViewModel>();
            int totalLogs = 0;

            var dateInitial = initial.ToString("yyyy-MM-dd HH:mm:ss");

            var dateFinal = final.ToString("yyyy-MM-dd HH:mm:ss");


            if (description == null)
                description = "";
            if (ip == null)
                ip = "";
            if (initial == null)
                initial = DateTime.Parse("01/01/2000 00:00:00");
                dateInitial = initial.ToString("yyyy-MM-dd");

            if (final == null)
                final = DateTime.Now;
                dateFinal = final.ToString("yyyy-MM-dd");


            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(apiUrl + "/search/" + description+ "/" + id + "/" +  ip + "/" +  dateInitial + "/" + dateFinal))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    listLogs = JsonConvert.DeserializeObject<List<LogViewModel>>(apiResponse);
                }

            
            }
            ViewBag.Total = listLogs.Count();
            var pages = 1;
            ViewData["qtdPagina"] = pages;
            ViewData["pagina"] = 1;
            return View(listLogs);
        }

        public async Task<IActionResult> GetAll()
        {
            List<LogViewModel> listLogs = new List<LogViewModel>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(apiUrl))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    listLogs = JsonConvert.DeserializeObject<List<LogViewModel>>(apiResponse);
                }

            }
            ViewBag.Total = listLogs.Count();
            var pages = 1;
            ViewData["qtdPagina"] = pages;
            ViewData["pagina"] = 1;
            return View(listLogs);
        }
    }
}

MVCLog/MVCLog/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bem Vindo</h1>
</div>

<h1>O Projeto</h1>
<h3>Inicio tela de Logs com Filtro pelo back-end ganhando assim desempenho no carregamento, pois o banco de dados contem mais de 60 mil registros</h3>
<a href="/log">Acesso</a>
<br />
<h3>Inicio tela de Logs com Filtro pelo javascript trazendo todos os registros</h3>
<a href="/log/GetAll">Acesso</a>
<br />
<h3>Observação</h3>
<h4>Contem um filtro para Ip,Id, Descrição e Data inicio e Fim</h4>

<br />

<h3>Para o front-end foi usando MVC ASP NET com Razor View</h3>

MVCLog/MVCLog/Views/Log/GetAll.cshtml
@model IEnumerable<MVCLog.Models.LogViewModel>

@{
    ViewData["Title"] = "Index";
}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>


<script>
    $(document).ready(function () {
        $('#example').dataTable();
    });

</script>
<h1>Tela de Logs</h1>
<h4>Nessa tela contem paginação e search via javascript, via post temos os filtros abaixo</h4>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    Filtro
</button>
<h4> Total de Logs: @ViewBag.Total</h4>

<input class="form-control" id="myInput" type="text" placeholder="Search..">
<br />
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ip)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>

        </tr>
    </thead>
    <tbody id="myTable">
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ip)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>

            </tr>
        }
    </tbody>
</table>
<br />
<br />
@using (Html.BeginForm("Index", "Log", FormMethod.Post))
{
    <div class="row">
        @{
            if ((int)ViewData["pagina"] <= 4)
            {

                var pageNum = 5;
                if ((int)ViewData["qtdPagina"] > 0 && (int)ViewData["qtdPagina"] < 5)
                {
                    pageNum = (int)ViewData["qtdPagina"];
                }
                <button type="submit" name="page" value="1" class="btn btn-light" href="#">Primeiro</button>

                for (int pages = 1; pages <= pageNum; pages++)
                {
                    if (pages == (int)ViewData["pagina"])
                    {
                        <button type="submit" name="page" value="@pages" href="#" class="active">@pages</button>
                    }
                    else
                    {
                        <button type="submit" name="page" value="@pages" class="btn btn-light" href="#">@pages</button>
                    }
                }
                <button type="submit" name="page" value="@ViewData["qtdPagina"]" class="btn btn-light" href="#">Último</button>

            }
            else
            {
                var num1 = 4;
                var num2 = 0;
                if ((int)ViewData["qtdPagina"] != (int)ViewData["pagina"])
                {
                    num1 = 3;
                    num2 = 1;
                }
                var pageinitial = (int)ViewData["pagina"] - num1;
                var pageFinal = (int)ViewData["pagina"] + num2;


                <button type="submit" name="page" value="1" class="btn btn-light" href="#">Primeiro</button>

                for (int pages = pageinitial; pages <= pageFinal; pages++)
                {
                    if (pages == (int)ViewData["pagina"])
                    {
                        <button type="submit" name="page" value="@pages" href="#" class="active">@pages</button>
                    }
                    else
                    {
                        <button type="submit" name="page" value="@pages" class="btn btn-light" href="#">@pages</button>
                    }
                }
                <button type="submit" name="page" value="@ViewData["qtdPagina"]" class="btn btn-light" href="#">Último</button>
            }
        }
    </div>
}
<br />
<br /><div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            @using (Html.BeginForm("Search", "Log", FormMethod.Post))
            {

                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Filtro</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    <h5>Id</h5>
                    <input name="id" id="id" class="form-control" />
                    <br />
                    <h5>Descrição</h5>
                    <p>Você pode colocar algum trecho da descrição ou palavra</p>
                    <input name="description" id="description" class="form-control" />
                    <br />
                    <h5>Ip</h5>
                    <input name="ip" id="ip" class="form-control" />
                    <h5>Data inicio</h5>
                    <input type="date" name="initial" id="initial" class="form-control" />
                    <br />
                    <h5>Data Final</h5>
                    <input type="date" name="final" id="final" class="form-control" />
                    <br />
                    <br />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    <button type="submit" class="btn btn-primary">Pesquisar</button>
                </div>
            }

        </div>
    </div>
</div>
<script>
    $('#myModal').on('shown.bs.modal', function () {
        $('#myInput').trigger('focus')
    })
</script>
<script>
    $(document).ready(function () {
        $("#myInput").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#myTable tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>

MVCLog/MVCLog/Views/Log/Index.cshtml
@model IEnumerable<MVCLog.Models.LogViewModel>

@{
    ViewData["Title"] = "Index";
}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>


<script>
    $(document).ready(function () {
        $('#example').dataTable();
    });

</script>
<h1>Tela de Logs</h1>
<h4>Nessa tela contem paginação e search via javascript, via post temos os filtros abaixo</h4>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    Filtro
</button>
<h4> Total de Logs: @ViewBag.Total</h4>

<input class="form-control" id="myInput" type="text" placeholder="Search..">
<br />
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ip)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>

        </tr>
    </thead>
    <tbody id="myTable">
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ip)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>

            </tr>
        }
    </tbody>
</table>
<br />
<br />
@using (Html.BeginForm("Index", "Log", FormMethod.Post))
{
    <div class="row">
        @{
            if ((int)ViewData["pagina"] <= 4)
            {

                var pageNum = 5;
                if ((int)ViewData["qtdPagina"] > 0 && (int)ViewData["qtdPagina"] < 5)
                {
                    pageNum = (int)ViewData["qtdPagina"];
                }
                <button type="submit" name="page" value="1" class="btn btn-light" href="#">Primeiro</button>

                for (int pages = 1; pages <= pageNum; pages++)
                {
                    if (pages == (int)ViewData["pagina"])
                    {
                        <button type="submit" name="page" value="@pages" href="#" class="active">@pages</button>
                    }
                    else
                    {
                        <button type="submit" name="page" value="@pages" class="btn btn-light" href="#">@pages</button>
                    }
                }
                <button type="submit" name="page" value="@ViewData["qtdPagina"]" class="btn btn-light" href="#">Último</button>

            }
            else
            {
                var num1 = 4;
                var num2 = 0;
                if ((int)ViewData["qtdPagina"] != (int)ViewData["pagina"])
                {
                    num1 = 3;
                    num2 = 1;
                }
                var pageinitial = (int)ViewData["pagina"] - num1;
                var pageFinal = (int)ViewData["pagina"] + num2;


                <button type="submit" name="page" value="1" class="btn btn-light" href="#">Primeiro</button>

                for (int pages = pageinitial; pages <= pageFinal; pages++)
                {
                    if (pages == (int)ViewData["pagina"])
                    {
                        <button type="submit" name="page" value="@pages" href="#" class="active">@pages</button>
                    }
                    else
                    {
                        <button type="submit" name="page" value="@pages" class="btn btn-light" href="#">@pages</button>
                    }
                }
                <button type="submit" name="page" value="@ViewData["qtdPagina"]" class="btn btn-light" href="#">Último</button>
            }
        }
    </div>
}
<br />
<br /><div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            @using (Html.BeginForm("Search", "Log", FormMethod.Post))
            {

                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Filtro</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    <h5>Id</h5>
                    <input name="id" id="id" class="form-control" />
                    <br />
                    <h5>Descrição</h5>
                    <p>Você pode colocar algum trecho da descrição ou palavra</p>
                    <input name="description" id="description" class="form-control" />
                    <br />
                    <h5>Ip</h5>
                    <input name="ip" id="ip" class="form-control" />
                    <h5>Data inicio</h5>
                    <input type="date" name="initial" id="initial" class="form-control" />
                    <br />
                    <h5>Data Final</h5>
                    <input type="date" name="final" id="final" class="form-control" />
                    <br />
                    <br />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    <button type="submit" class="btn btn-primary">Pesquisar</button>
                </div>
            }

        </div>
    </div>
</div>
<script>
    $('#myModal').on('shown.bs.modal', function () {
        $('#myInput').trigger('focus')
    })
</script>
<script>
    $(document).ready(function () {
        $("#myInput").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#myTable tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>

MVCLog/MVCLog/Views/Log/Search.cshtml
@model IEnumerable<MVCLog.Models.LogViewModel>

@{
    ViewData["Title"] = "Index";
}

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">

<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
<script src="//cdn.datatables.net/plug-ins/1.10.7/integration/bootstrap/3/dataTables.bootstrap.js"></script>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">


<script>
    $(document).ready(function () {
        $('#example').dataTable();
    });

</script>
<h1>Tela de Logs com Pesquisa</h1>
<a href="/log" class="btn btn-primary" >
    Voltar
</a>
<h4> Total de Logs pesquisado: @ViewBag.Total</h4>

<input class="form-control" id="myInput" type="text" placeholder="Search..">
<br />
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ip)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>

        </tr>
    </thead>
    <tbody id="myTable">
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ip)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>

            </tr>
        }
    </tbody>
</table>
<br />
<br />
@using (Html.BeginForm("Index", "Log", FormMethod.Post))
{
    <div class="row">
        @{
            if ((int)ViewData["pagina"] <= 4)
            {

                var pageNum = 5;
                if ((int)ViewData["qtdPagina"] > 0 && (int)ViewData["qtdPagina"] < 5)
                {
                    pageNum = (int)ViewData["qtdPagina"];
                }
                <button type="submit" name="page" value="1" class="btn btn-light" href="#">Primeiro</button>

                for (int pages = 1; pages <= pageNum; pages++)
                {
                    if (pages == (int)ViewData["pagina"])
                    {
                        <button type="submit" name="page" value="@pages" href="#" class="active">@pages</button>
                    }
                    else
                    {
                        <button type="submit" name="page" value="@pages" class="btn btn-light" href="#">@pages</button>
                    }
                }
                <button type="submit" name="page" value="@ViewData["qtdPagina"]" class="btn btn-light" href="#">Último</button>

            }
            else
            {
                var num1 = 4;
                var num2 = 0;
                if ((int)ViewData["qtdPagina"] != (int)ViewData["pagina"])
                {
                    num1 = 3;
                    num2 = 1;
                }
                var pageinitial = (int)ViewData["pagina"] - num1;
                var pageFinal = (int)ViewData["pagina"] + num2;


                <button type="submit" name="page" value="1" class="btn btn-light" href="#">Primeiro</button>

                for (int pages = pageinitial; pages <= pageFinal; pages++)
                {
                    if (pages == (int)ViewData["pagina"])
                    {
                        <button type="submit" name="page" value="@pages" href="#" class="active">@pages</button>
                    }
                    else
                    {
                        <button type="submit" name="page" value="@pages" class="btn btn-light" href="#">@pages</button>
                    }
                }
                <button type="submit" name="page" value="@ViewData["qtdPagina"]" class="btn btn-light" href="#">Último</button>
            }
        }
    </div>
}
<br />
<br /><div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Filtro</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Id</h5>
                <input name="id" id="id" class="form-control" />
                <br />
                <h5>Descrição</h5>
                <p>Você pode colocar algum trecho da descrição ou palavra</p>
                <input name="id" id="id" class="form-control" />
                <br />
                <h5>Ip</h5>
                <input name="ip" id="ip" class="form-control" />
                <h5>Data inicio</h5>
                <input type="date" name="initial" id="initial" class="form-control" />
                <br />
                <h5>Data Final</h5>
                <input type="date" name="final" id="final" class="form-control" />
                <br />
                <br />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary">Pesquisar</button>
            </div>
        </div>
    </div>
</div>
<script>
    $('#myModal').on('shown.bs.modal', function () {
        $('#myInput').trigger('focus')
    })
</script>
<script>
    $(document).ready(function () {
        $("#myInput").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#myTable tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>

MVCLog/MVCLog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCLog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCLog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MVCLog - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>